---

- hosts: test
  become: true
  gather_facts: true
  tasks:
  - name: Ensure "enabled=1 is in section "[DEFAULT]" in specified file
    community.general.ini_file:
      path: "{{ aliases }}"
      section: DEFAULT
      option: enabled
      value: 0
      state: present
      no_extra_spaces: yes
      mode: '0644'
      backup: true
