---
- name: Recursively find template files
  ansible.builtin.find:
    paths: "{{ role_path }}/templates/"
    recurse: yes
  register: templates_list

- name: Ensure target directory exists
  ansible.builtin.file:
    dest: "/usr/local/apnscp/resources/templates/plans/{{ plan.name }}/"
    state: directory
    mode: '0755'
    group: apnscp
    owner: apnscp

- name: Ensure all template files are rendered
  ansible.builtin.template:
    src: '{{ item.path }}'
    dest: "/usr/local/apnscp/resources/templates/plans/{{ plan.name }}/{{ item.path | basename | splitext | first }}"
    mode: '0644'
    group: apnscp
    owner: apnscp
    msg:
  with_items: "{{ templates_list.files }}"
